# general configuration
debug: true
base_url: /<%= initFolder %>/

# folders
twigs: /twigs # main twigs folder
sections: /twigs/sections # sections autoloader

# base route -> required in seo.csv
defaultRoute: home 

# markdown processor
enableMarkdown: false

# REQUIRED # import as it generates the routing system -> template at
routing:
  url: seo.csv
  format: csv
  indexColumn: name
  exposeJS: false
  exposeTWIG: true

# other data imports
dataImports:
  songs:
    url: https://docs.google.com/spreadsheets/d/1ZTJOMeTe7gbgK3oq30kNycMwRAGHNpa9vkfiJ4MZmJA/export?gid=0&format=csv
    format: csv
    indexColumn:
    exposeJS: true
    exposeTWIG: true
    preprocess: myDataProcessorSample


# advanced configuration
defaultControler: Controller\ApplicationController::indexAction